name: Manually workflow experiment
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Person to greet'
                required: true
                default: 'Mona the Octocat'
            home:
                description: 'location'
                required: false
                default: 'The Octoverse'

jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            # create a check run
            - uses: octokit/request-action@v2.x
              id: create_check_run
              with:
                  route: POST /repos/:repository/check-runs
                  repository: ${{ github.repository }}
                  name: 'Test check run'
                  head_sha: ${{ github.sha }}
                  output: |
                      title: Test check run title
                      summary: A summary of the test check run
                      images:
                        - alt: Test image
                          image_url: https://octodex.github.com/images/jetpacktocat.png
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: |
                  echo "Hello ${{ github.event.inputs.name }}!"
                  echo "- in ${{ github.event.inputs.home }}!"
                  sleep 10
            # Update check run to completed, succesful status
            - uses: octokit/request-action@v2.x
              id: set_status
              with:
                  route: PATCH /repos/:repository/check-runs/:check_run_id
                  repository: ${{ github.repository }}
                  # mediaType: |
                  #     previews:
                  #       - antiope
                  check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
                  conclusion: 'success'
                  status: 'completed'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
