name: 'example'
on:
    pull_request:
        types:
            - labeled
            - unlabeled

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              id: my-action
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  labelRequested: e2e:request
                  labelQueued: e2e:queued
                  labelRunning: e2e:running
            - name: Simulate e2e run for 20 seconds
              if: ${{steps.my-action.outputs.run}}
              run: sleep 20
