name: 'example'
on:
    pull_request:
        types:
            - labeled
            - unlabeled

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - id: my-action
              uses: ./
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  labelRequested: e2e:request
                  labelQueued: e2e:queued
                  labelRunning: e2e:running
            - id: e2e
              name: Simulate e2e run for 20 seconds
              if: ${{ steps.my-action.outputs.run }}
              run: sleep 20 && exit 1
            - uses: LouisBrunner/checks-action@v0.1.0
              if: ${{ steps.my-action.outputs.run && always() }}
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: Test E2E
                  # conclusion: ${{ job.status }}
                  conclusion: ${{ steps.e2e.outcome }}
                  # output: |
                  #     {"summary":${{ steps.test.outputs.summary }}}
