name: 'example'
on:
  pull_request:
    types:
      - labeled

jobs:
  e2e:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: my-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labelRequested: e2e:request
          labelQueued: e2e:queued
          labelRunning: e2e:running
      - name: Show result
        run: echo "${{steps.my-action.outputs.time}}"
