name: 'build-test'
on: # rebuild any PRs and main branch changes
  - pull_request
  - push
  # pull_request:
  # push:
  #   branches:
  #     - main
  #     - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npx tsc
      - run: npx ncc build --source-map
      # - run: |
      #     npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: my-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          milliseconds: 1000
      - name: Show result
        run: echo "${{steps.my-action.outputs.time}}"

# on: push

# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/github-script@v3
#         id: set-result
#         with:
#           # github, context, core, io
#           script: |
#             "use strict";
#             Object.defineProperty(exports, "__esModule", { value: true });
#             console.log('github', Object.keys(github));
#             console.log('context', Object.keys(context));
#             console.log('core', Object.keys(core));
#             console.log('io', Object.keys(io));
#             return `Hello! ${typeof github} ${typeof context} ${typeof core} ${typeof io}`
#           result-encoding: string
#       - name: Get result
#         run: echo "${{steps.set-result.outputs.result}}"
#       - name: Checkout
#         uses: actions/checkout@v2
#       - uses: actions/github-script@v3
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             const script = require(`${process.env.GITHUB_WORKSPACE}/dummy.js`)
#             console.log(script({github, context}))
