on: push

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: set-result
        with:
          # github, context, core, io
          script: |
            return `Hello! ${typeof github} ${typeof context} ${typeof core} ${typeof io}`
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/dummy.js`)
            console.log(script({github, context}))
